# -----------------------------------------------------
# Jekyll Site Configuration for johnsosoka.com
# Author: john sosoka
# Date: 2021-11-08, 2023-07-19
# -----------------------------------------------------
theme: jscom_ice

# Basic Settings
title: johnsosoka.com
description: Writing Code in Boise.
site_est_year: 2020
lang: en-US
timezone: US/Mountain

# open graph image
og_image: https://media.johnsosoka.com/old/img/ogp.png

# John Landing Page
author:
  name: John Sosoka
  bio: >-
    <a href="https://github.com/johnsosoka" target="_blank" rel="noopener">@github</a><br>
    Writing Code in Boise.
  username: jsosoka
  facebook: 100070345623723
  email: web@johnsosoka.com
  avatar: https://media.johnsosoka.com/old/img/avatar-small.jpg

# URL Settings
url: "https://www.johnsosoka.com"

# Collection Settings
collections:
  blog:
    output: true
  notes:
    output: true
  pages:
    output: true

# Markdown Settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Homepage Post Limit
number_of_posts: 5

# Build Settings
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

# Plugin Settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Contact Form Settings
contact:
  api:
    url: https://api.johnsosoka.com/v1/contact
