source "https://rubygems.org"
#
#     bundle install
#     bundle exec jekyll serve
#

gem "jekyll", "~> 4.3.2"

group :jekyll_plugins do
  # jscom theme - using local path for development
  gem "jscom_ice", '~> 1.1.0'

end
