source "https://rubygems.org"
#
#     bundle install
#     bundle exec jekyll serve
#

gem "jekyll", "~> 4.3.2"
gem "csv"
gem "logger"
gem "base64"

group :jekyll_plugins do
  # jscom theme
  gem "jscom_ice", "~> 1.4.1"

end
