# -----------------------------------------------------------
# Deploy Jekyll site to S3 and invalidate CloudFront cache
# Author: John Sosoka
# Date: 2023-07-14
# -----------------------------------------------------------

name: Deploy to S3 and Invalidate CloudFront

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build site
        run: |
          cd website
          bundle install
          bundle exec jekyll build
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $
          aws-secret-access-key: $
          aws-region: $

      - name: Upload to S3
        run: |
          if [[ "$" == "pull_request" ]]; then
            aws s3 sync ./website/_site/ s3://$
          else
            aws s3 sync ./website/_site/ s3://$
            aws s3 sync ./website/_site/ s3://$
          fi

      - name: Invalidate CloudFront Distribution(s)
        run: |
          if [[ "$" == "pull_request" ]]; then
            aws cloudfront create-invalidation --distribution-id $ --paths "/*"
          else
            aws cloudfront create-invalidation --distribution-id $ --paths "/*"
            aws cloudfront create-invalidation --distribution-id $ --paths "/*"
          fi